In [2]:
import numpy as np

m = np.array([[1,2],[1,2]])

print(m.shape)

(2, 2)


In [4]:
m = np.array([[1,2,3],[1,2,3],[1,2,3]])

print(m.shape)

(3, 3)


In [5]:
m = np.array([[1,2],[1,2],[1,2]])

print(m.shape)

(3, 2)


In [6]:
m = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

print(m.shape)

(4, 4)


In [7]:
m = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]])

print(m.shape)

(5, 3)


In [8]:
m = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,3,4]])

print(m.shape)

(3, 5)


In [9]:
m = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,3,4],[1,2,3,4,5],[1,2,3,4,5]])

print(m.shape)

(5, 5)


In [10]:
m = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,3,4],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

print(m.shape)

(6, 5)


In [11]:
m = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,3],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

print(m.shape)

(6, 4)


In [14]:
m = np.array([[1,2],[1,2],[1,2]])

print(m.shape)
print(m.reshape(2,3))

(3, 2)
[[1 2 1]
 [2 1 2]]


In [16]:
m = np.array([[3,4],[1,2],[7,9]])

print(m.shape)
print(m.reshape(2,3))

print(m.shape)

(3, 2)
[[3 4 1]
 [2 7 9]]
(3, 2)


In [22]:
a = np.array([[2,4,6.7],[3,5,8],[5,8,9]])
print(a.size)
print(a.itemsize)

9
8


In [23]:
#print no of byte occupied in the memory by each item.
print(a.itemsize)

8


In [24]:
a = np.array([[2,4,6],[3,5,8],[5,8,9]])
print(a.size)
print(a.itemsize)  #integer int32 

9
4


In [26]:

a.max()

9

In [27]:
a.min()

2

In [29]:
a.dtype

dtype('int32')

In [30]:
# memory address of data.
a.data

In [32]:
a = np.array([[2,4,6],[3,5,8],[5,8,9]], dtype='float64')

a

array([[2., 4., 6.],
       [3., 5., 8.],
       [5., 8., 9.]])

In [33]:
a.itemsize

8

In [34]:
a.shape

(3, 3)

In [36]:
a.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [37]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a = x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
a = np.arange(35).reshape(5,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [40]:
a.ndim

2

In [41]:
np.ones((2,3,4),dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [42]:
np.empty((5,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511562e-306, 1.78019082e-306],
       [1.89146896e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.42417221e-306,
        1.42419530e-306, 1.37962456e-306],
       [1.11260959e-306, 9.34603679e-307, 1.11260348e-306,
        1.33511562e-306, 9.34603679e-307],
       [1.11260348e-306, 1.33511562e-306, 1.42410974e-306,
        2.10077583e-312, 2.10081501e-312]])

In [44]:
np.arange(10,30,5)


array([10, 15, 20, 25])

In [46]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [50]:
a= np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)


[20 30 40 50]
[0 1 2 3]


In [55]:
c=a-b
print(c)

[20 29 38 47]


In [53]:
b**2


array([0, 1, 4, 9], dtype=int32)

In [58]:
k = np.random.random((2,3))

k


array([[0.8455335 , 0.84525923, 0.9468771 ],
       [0.67385883, 0.30465953, 0.7038194 ]])