In [6]:
import numpy as np

x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [3]:
x.shape

(4,)

In [7]:
x = np.array([[1,2,3,4,],[2,4,6,8]])

In [8]:
x

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [9]:
x.shape

(2, 4)

In [10]:
x = np.array([[3,4,],[6,8]])
x

array([[3, 4],
       [6, 8]])

In [11]:
x = np.array([[1,2,3,4,],[2,4,6,8],[2,3,4,5]])

x

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [2, 3, 4, 5]])

In [12]:
x.shape

(3, 4)