In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree


In [12]:
#balance_data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data', sep=',', header=True)
balance_data=pd.read_csv('balance-scale.data',sep=',',header=None)

In [13]:
balance_data

0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]

In [14]:
len(balance_data)

625

In [15]:
balance_data.shape

(625, 5)

In [17]:
y = balance_data.iloc[:,0]
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0, 2, 1, 0, 2, 2, 2, 1, 2, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 0, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0,
       2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2,
       1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1, 1,
       2, 2, 2, 1, 0, 2, 2, 2, 1, 1, 0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 1,
       0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1,

In [18]:
x=balance_data.iloc[:,1:5]
#y=balance_data.iloc[:,0]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=45)

In [20]:
from sklearn.tree import DecisionTreeClassifier
dt_gini=DecisionTreeClassifier(criterion='gini',random_state=100)
dt_gini.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

In [22]:
pred=dt_gini.predict(x_test)
pred

array([2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1,
       0, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 0, 2, 1, 2, 1, 2,
       2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 2,
       2, 2, 2, 1, 1, 1, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 1, 0, 2,
       1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 0, 1, 2,
       2, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 1, 1,
       2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 0, 2, 0, 1, 1, 1, 1,
       2, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 0, 2, 2, 1, 1, 2, 1, 1, 2,
       2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 0, 1, 2, 0, 1, 1, 1, 2, 2, 2, 1, 2,
       2, 2, 1, 1, 1, 2, 1, 1, 2])

In [23]:
accuracy_score(y_test,pred)

0.7729468599033816

In [33]:
from sklearn.tree import DecisionTreeClassifier
dt_en=DecisionTreeClassifier(criterion='entropy',random_state=100)
dt_en.fit(x_train,y_train)

pred=dt_en.predict(x_test)
pred

array([2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 1, 1, 1, 0, 2, 1,
       0, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 0, 0, 2, 1, 2, 1, 2,
       2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2,
       2, 2, 2, 1, 2, 1, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 1, 0, 2,
       1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 0, 1, 2,
       2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 1, 1,
       2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       2, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2,
       2, 2, 1, 0, 1, 1, 2, 0, 2, 2, 0, 1, 2, 0, 1, 1, 1, 2, 2, 2, 1, 2,
       2, 2, 1, 1, 1, 2, 1, 1, 2])

In [24]:
def dectree(cr,rs):
    m=DecisionTreeClassifier(criterion=cr,random_state=rs)
    m.fit(x_train,y_train)
    pred=m.predict(x_test)
    print(accuracy_score(y_test,pred))

In [28]:
dectree('gini',48)

0.7874396135265701


In [30]:
dectree('entropy',47)

0.7729468599033816


In [31]:
from sklearn.model_selection import cross_val_score
gnbscores = cross_val_score(dt_gini,x,y,cv=8)
print(gnbscores)
print(gnbscores.mean(),gnbscores.std())

[0.49367089 0.65384615 0.67948718 0.78205128 0.73076923 0.74358974
 0.79487179 0.55128205]
0.6786960402466733 0.10135870515844712


In [34]:
from sklearn.model_selection import cross_val_score
gnbscores = cross_val_score(dt_en,x,y,cv=8)
print(gnbscores)
print(gnbscores.mean(),gnbscores.std())

[0.49367089 0.66666667 0.67948718 0.79487179 0.70512821 0.74358974
 0.78205128 0.5       ]
0.6706832197338527 0.10890777974409653


In [35]:
dt_gini.predict([[4,4,3,3]])

array([1])

In [36]:
dt_gini.predict([[1,1,1,5]])

array([2])

In [37]:
dt_gini.predict([[1,1,1,1]])

array([0])

In [38]:
dt_en.predict([[1,1,1,5]])

array([2])

In [39]:
dt_en.predict([[4,4,3,3]])

array([1])

In [40]:
import joblib
joblib.dump(dt_gini,"dtginimodel.obj")

['dtginimodel.obj']

In [41]:
p=joblib.load("dtginimodel.obj")

In [42]:
p.predict([[4,4,2,5]])

array([1])

In [44]:
import numpy as np
t = np.array([1,1,2,3])
t=t.reshape(1,-1)
print(p.predict(t))

[2]
